version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb-dev
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD:-password123}
      MONGO_INITDB_DATABASE: vocabulary
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_dev:/data/db
    networks:
      - devops-network

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express-dev
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USERNAME:-admin}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD:-password123}
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_EXPRESS_USERNAME:-admin}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_EXPRESS_PASSWORD:-admin123}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_USERNAME:-admin}:${MONGO_PASSWORD:-password123}@mongodb:27017/
    ports:
      - "8081:8081"
    depends_on:
      - mongodb
    networks:
      - devops-network
    restart: unless-stopped

  # Development App - Einfache Lösung
  app:
    build:
      context: ./app
      dockerfile: Dockerfile.dev
    container_name: sprachenlern-app-dev
    ports:
      - "3000:3000"
    environment:
      MONGODB_URL: mongodb://${MONGO_USERNAME:-admin}:${MONGO_PASSWORD:-password123}@mongodb:27017/vocabulary?authSource=admin
      GOOGLE_TTS_API_KEY: ${GOOGLE_TTS_API_KEY:-mock-key}
      NODE_ENV: development
    depends_on:
      - mongodb
    volumes:
      # Source-Code Mount für Live-Entwicklung
      - ./app:/app:delegated  # delegated für bessere Performance
      # Named Volume für node_modules
      - node_modules_dev:/app/node_modules
      - audio_files_dev:/app/public/audio
    networks:
      - devops-network
    # Als root laufen lassen (Development only!)
    user: "0:0"
    # Alternative: Deine Host UID/GID verwenden
    # user: "${UID:-1000}:${GID:-1000}"

volumes:
  mongodb_data_dev:
  audio_files_dev:
  node_modules_dev:

networks:
  devops-network:
    driver: bridge