version: '3.8'

services:
  # MongoDB Database (bleibt weitgehend gleich)
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: vocabulary
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  # Mongo Express (NEU!)
  mongo-express:
    image: mongo-express:latest
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin123
    ports:
      - "8081:8081"
    depends_on:
      - mongodb

  # Sprachenlern-App (vorher backend)
  app:
    image: ${DOCKER_USERNAME}/sprachenlern-app:${IMAGE_TAG}
    ports:
      - "3000:3000"
    environment:
      MONGODB_URI: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongodb:27017/vocabulary?authSource=admin
      GOOGLE_TTS_API_KEY: ${GOOGLE_TTS_API_KEY}
      NODE_ENV: production
    depends_on:
      - mongodb
    volumes:
      - audio_files:/app/public/audio

volumes:
  mongodb_data:
  audio_files:

networks:
  default:
    driver: bridge
