name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  # App Build und Test (vorher backend)
  app:
    runs-on: ubuntu-latest
    env:
      NODE_VERSION: "22"

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"
          cache-dependency-path: "./app/package-lock.json"

      - name: Install App Dependencies
        working-directory: app
        run: npm ci

      # Tests erstmal deaktiviert
      # - name: Test App
      #   working-directory: app
      #   run: npm test

      - name: Build App
        working-directory: app
        run: npm run build || echo "No build script found"

  # Docker Build and Push (angepasst)
  docker:
    needs: [app]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Generate Version Tag
        id: version
        run: |
          SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-7)
          VERSION_TAG=$(date +%Y%m%d)-${SHORT_SHA}
          echo "version=${VERSION_TAG}" >> $GITHUB_OUTPUT

      - name: Build and Push App Image
        uses: docker/build-push-action@v4
        with:
          context: ./app
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/sprachenlern-app:latest
            ${{ secrets.DOCKER_USERNAME }}/sprachenlern-app:${{ steps.version.outputs.version }}
