name: Delivery – Build & Push Image

on:
  push:
    branches: [ main ]     # nur nach Merge auf main
  workflow_dispatch:        # optional: manuell auslösbar

permissions:
  contents: read
  packages: write

jobs:
  docker_build_push:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Übergangs-Tag (SemVer kommt im nächsten Schritt)
      - name: Compute Image Tag
        id: ver
        run: |
          echo "tag=$(date +%Y%m%d)-${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: ./app
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/sprachenlern-app:${{ steps.ver.outputs.tag }}
            ${{ secrets.DOCKER_USERNAME }}/sprachenlern-app:latest

      - name: Output image tag
        run: echo "Image tag: ${{ steps.ver.outputs.tag }}"
